version: '3.9'

services:

  backend:
    build: ./
    container_name: linked_backend
    command: bash entrypoint.sh
    volumes:
      - .:/usr/src/app/
    ports:
      - 80:8000
    depends_on:
      - linked_db
    env_file:
      - ./.env

  linked_db:
    image: postgres:12
    container_name: linked_db
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"